query popular {
  popular(page: 0) {
    data {
      id
      slug
      name
      type
      price
      stock
      img
      images
      time
      ratings
      reviews
      vendor {
        id
        firstName
        lastName
        phone
        email
        info {
          store
          storePhotos
        }
      }
    }
    count
    pageSize
    page
  }
}
