mutation saveProduct(
  $id: String!
  $name: String
  $slug: String
  $description: String
  $type: String
  $city: String
  $price: Float
  $mrp: Float
  $stock: Int
  $tax: Float
  $img: String
  $images: [String]
  $time: String
  $active: Boolean
  $hot: Boolean
  $featured: Boolean
  $trending: Boolean
  $sale: Boolean
  $new: Boolean
  $recommended: Boolean
  $position: Int
  $category: ID
  $categories: [ID!]
  $collections: [ID]
  $brand: ID
  $parentBrand: ID
  $variants: [ID!]
  $popularity: Int
  $sku: String
  $hsn: String
  $group: String
  $colorCode: String
  $colorName: String
  $size: ID
  $barcode: String
  $title: String
  $metaDescription: String
  $keywords: String
  $itemId: String
  $warranty: String
  $ageMin: Int
  $ageMax: Int
  $ageUnit: String
  $styleCode: String
  $eanNo: String
  $articleCode: String
  $productMasterId: String
  $currency: String
  $manufacturer: String
  $returnInfo: String
  $gender: String
  $condition: String
  $gtin: String
  $countryOfOrigin: String
  $cgst: Float
  $sgst: Float
  $igst: Float
  $weight: Float
  $replaceAllowed: Boolean
  $returnAllowed: Boolean
  $returnValidityInDays: Int
  $length: Float
  $width: Float
  $height: Float
  $relatedProducts: [ID!]
  $specifications: [ID!]
  $store: ID
  $files: [String]
  $sizechart: String
  $mfgDate: String
  $batchNo: String
  $expiryDate: String
) {
  saveProduct(
    id: $id
    name: $name
    slug: $slug
    description: $description
    type: $type
    city: $city
    price: $price
    mrp: $mrp
    stock: $stock
    tax: $tax
    img: $img
    images: $images
    time: $time
    active: $active
    category: $category
    categories: $categories
    collections: $collections
    brand: $brand
    parentBrand: $parentBrand
    popularity: $popularity
    sku: $sku
    hsn: $hsn
    barcode: $barcode
    group: $group
    colorCode: $colorCode
    colorName: $colorName
    size: $size
    position: $position
    variants: $variants
    hot: $hot
    featured: $featured
    trending: $trending
    sale: $sale
    new: $new
    recommended: $recommended
    title: $title
    metaDescription: $metaDescription
    keywords: $keywords
    itemId: $itemId
    warranty: $warranty
    ageMin: $ageMin
    ageMax: $ageMax
    ageUnit: $ageUnit
    styleCode: $styleCode
    eanNo: $eanNo
    articleCode: $articleCode
    productMasterId: $productMasterId
    currency: $currency
    manufacturer: $manufacturer
    returnInfo: $returnInfo
    gender: $gender
    condition: $condition
    gtin: $gtin
    countryOfOrigin: $countryOfOrigin
    cgst: $cgst
    sgst: $sgst
    igst: $igst
    relatedProducts: $relatedProducts
    specifications: $specifications
    weight: $weight
    replaceAllowed: $replaceAllowed
    returnAllowed: $returnAllowed
    returnValidityInDays: $returnValidityInDays
    length: $length
    width: $width
    height: $height
    store: $store
    files: $files
    sizechart: $sizechart
    mfgDate: $mfgDate
    batchNo: $batchNo
    expiryDate: $expiryDate
  ) {
    id
    name
    description
    slug
    type
    city
    price
    mrp
    stock
    tax
    img
    images
    time
    active
    popularity
    sku
    hsn
    group
    brand
    parentBrand
    color {
      color_code
    }
    size
    barcode
    position
    trending
    featured
    hot
    new
    sale
    recommended
    title
    metaDescription
    keywords
    itemId
    warranty
    ageMin
    ageMax
    ageUnit
    styleCode
    styleId
    eanNo
    articleCode
    productMasterId
    currency
    manufacturer
    countryOfOrigin
    returnInfo
    gender
    condition
    gtin
    cgst
    sgst
    igst
    vendor
    specifications {
      id
      name
      value
    }
    relatedProducts {
      id
      name
      slug
      img
    }
    colorGroup
    sizeGroup
    variants
    collections
    weight
    length
    width
    height
    returnAllowed
    replaceAllowed
    returnValidityInDays
    store
    files
    sizechart
    batchNo
    mfgDate
    expiryDate
  }
}
# {
#   "id": "new",
#   "name": "test product 1",
#   "category": "60828b3a300e0a4504e1234f",
#   "categories": ["60828b3a300e0a4504e1234f","60828b3a300e0a4504e12351","608290d28bf5970d5c7d79eb"],
#   "brand": "6086970ea3d8e916e8c897bf",
#   "color": "6086970ea3d8e916e8c897bf",
#   "size": "6086970ea3d8e916e8c897bf",
#   "relatedProducts": ["6087c1a325c8f03d202051dd","6087c1a025c8f03d202051da"]
# }
