mutation {
  addAddress(
    firstName: "sunil"
    lastName: "jayas"
    type: "home"
    address: "53 shivpuri"
    town: "ggc"
    district: "swm"
    city: "ggc"
    country: "india"
    state: "raj"
    zip: 322201
    phone: "8003423344"
    lat: 27.2046
    lng: 77.4977
  ) {
    id
    firstName
    lastName
    address
    town
    district
    city
    type
    country
    state
    zip
    phone
    lat
    lng
  }
}
