query me {
  me {
    id
    firstName
    lastName
    email
    phone
    gender
    role
    verified
    active
    provider
    active
    avatar
    referralCode
    currentBalance
    storeName
    banner
    store
    roles {
      id
      name
      roles
    }
    # product_sold
    address {
      id
      email
      firstName
      lastName
      address
      town
      city
      district
      state
      country
      zip
      phone
      active
      # lat
      # lng
    }
    info {
      public
      store
      storePhotos
    }
    businessDetail {
      bankName
      accountNo
      accountHolderName
      ifsc
    }
    # plan
  }
}
