mutation register(
  $email: String!
  $password: String!
  $passwordConfirmation: String!
  $firstName: String
  $lastName: String
  $referrer: String
) {
  register(
    email: $email
    password: $password
    passwordConfirmation: $passwordConfirmation
    firstName: $firstName
    lastName: $lastName
    referrer: $referrer
  ) {
    id
    email
    firstName
    lastName
    city
    phone
    role
    verified
    active
    avatar
    provider
    createdAt
    updatedAt
  }
}
