query user($id: String!) {
  user(id: $id) {
    id
    email
    firstName
    lastName
    avatar
    city
    phone
    role
    verified
    active
    productSold
    shippingCharges
    freeShippingOn
    luluCustomerNo
    plan
    storeName
    banner
    createdAt
    updatedAt
  }
}
