query size($id: ID!) {
  size(id: $id) {
    id
    name
    slug
    info
    img
    sort
    featured
    active
    createdAt
    updatedAt
    store {
      id
      name
      email
    }
  }
}
