query collection($id: ID!) {
  collection(id: $id) {
    id
    name
    description
    active
    images
    img
    q
    sort
    type
    user {
      firstName
    }
    products {
      id
      name
    }
    createdAt
    updatedAt
  }
}
