query brand1($id: String, $slug: String) {
  brand1(id: $id, slug: $slug) {
    id
    brandId
    name
    slug
    img
    position
    active
    featured
    info
    meta
    metaTitle
    metaDescription
    metaKeywords
    facebookUrl
    instaUrl
    twitterUrl
    linkedinUrl
    youtubeUrl
    pinterestUrl
    googleUrl
    parent
    store
    user
    createdAt
    updatedAt
  }
}
