query myCustomers(
  $page: Int
  $skip: Int
  $limit: Int
  $search: String
  $sort: String
) {
  myCustomers(
    page: $page
    skip: $skip
    limit: $limit
    search: $search
    sort: $sort
  ) {
    data {
      _id {
        id
        orderNo
        otp
        amount {
          qty
          total
        }
        paymentOrderId
        user {
          firstName
          lastName
          phone
        }
        delivery {
          otp
          finish {
            lat
            lng
          }
        }
        address {
          address
          firstName
          lastName
          phone
        }
        createdAt
        updatedAt
      }
      items {
        pid
        name
        status
        price
        qty
        img
        tracking
        vendor {
          firstName
          lastName
          address {
            address
          }
          phone
          store
        }
      }
    }
  }
  settings {
    orderStatuses {
      status
      title
      body
      icon
    }
  }
}
