query emailTemplates(
  $page: Int
  $search: String
  $limit: Int
  $sort: String
  $store: ID
) {
  emailTemplates(
    page: $page
    search: $search
    limit: $limit
    sort: $sort
    store: $store
  ) {
    count
    page
    pageSize
    data {
      id
      name
      title
      description
      content
      link
      active
      createdAt
      updatedAt
      user {
        id
        firstName
        email
        phone
      }
      store {
        id
        name
        email
      }
    }
  }
}

# query emailTemplates($folder: String, $name: String) {
#   emailTemplates(folder: $folder, name: $name)
# }
