query cities($page: Int, $search: String, $limit: Int, $sort: String) {
  cities(page: $page, search: $search, limit: $limit, sort: $sort) {
    count
    page
    pageSize
    data {
      id
      name
      user {
        id
        firstName
      }
      lat
      lng
      active
      createdAt
      updatedAt
    }
  }
}
