mutation saveCity(
  $id: String
  $name: String
  $lat: Float
  $lng: Float
  $active: Boolean
) {
  saveCity(id: $id, name: $name, lat: $lat, lng: $lng, active: $active) {
    id
    name
    user {
      id
      firstName
    }
    lat
    lng
    active
    createdAt
    updatedAt
  }
}
